import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { Loader2, AlertTriangle } from "lucide-react";

import { SiteReport } from "@/components/dashboard/SiteReport";
import { WcagScorecard, EaaReadiness } from "@/components/dashboard/Compliance";
import { ScoreBadge } from "@/components/dashboard/ScoreBadge";
import { SeveritySummary } from "@/components/dashboard/severity";
import { ScanPoller } from "@/components/scan/ScanPoller";
import { Button } from "@/components/ui/Button";
import { db, schema } from "@/lib/server/db";
import { getSitePages, rollupByRule } from "@/lib/server/report";
import { summarizeConformance } from "@/lib/wcag";
import { SITE_NAME, CTA } from "@/lib/site";

export const metadata: Metadata = { title: "Your scan", robots: { index: false } };
export const dynamic = "force-dynamic";

/** Sign-up nudge shown on the public trial result. */
function UpsellBanner() {
  return (
    <div className="mt-8 flex flex-col items-start gap-4 border-[3px] border-[var(--ink)] bg-yellow p-5 shadow-ink sm:flex-row sm:items-center sm:justify-between">
      <p className="font-display font-bold text-[var(--ink)]">
        This is one page. Monitor your whole site — every release, automatically.
      </p>
      <Button href={CTA.primary.href} variant="blue" size="md" className="shrink-0">
        {CTA.primary.label}
      </Button>
    </div>
  );
}

export default async function PublicScanPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  if (!token) notFound();

  const rows = await db
    .select()
    .from(schema.sites)
    .where(eq(schema.sites.shareToken, token))
    .limit(1);
  const site = rows[0];
  if (!site) notFound();

  // Share token in tow so screenshot URLs authorize for this anonymous viewer.
  const { pages, counts } = await getSitePages(site.id, { shareToken: token });
  const page = pages[0];
  const scanning = !page || page.status === "queued" || page.status === "running";
  const errored = page?.status === "error";

  const host = site.origin ? site.origin.replace(/^https?:\/\//, "") : site.name;

  return (
    <div className="min-h-screen bg-bg">
      <div className="mx-auto w-full max-w-[1000px] px-5 py-10 sm:px-8">
        <div className="border-b border-[var(--color-panel-line)] pb-6">
          <p className="mb-2 font-display text-xs font-bold uppercase tracking-[0.12em] text-fg-soft">
            Free accessibility scan
          </p>
          <h1 className="text-3xl text-fg sm:text-4xl break-words">{host}</h1>
        </div>

        {scanning ? (
          <div className="mt-10 flex flex-col items-center gap-4 py-16 text-center">
            <Loader2 className="size-8 animate-spin text-blue" aria-hidden="true" />
            <p className="font-display text-xl font-bold text-fg">Scanning {host}…</p>
            <p className="max-w-md text-fg-soft">
              We&apos;re loading the page the way assistive tech does — keyboard, screen reader, and
              color checks. This usually takes under a minute; the report appears here automatically.
            </p>
            <ScanPoller />
          </div>
        ) : errored ? (
          <div className="mt-10 flex flex-col items-center gap-4 py-16 text-center">
            <AlertTriangle className="size-8 text-pink" aria-hidden="true" />
            <p className="font-display text-xl font-bold text-fg">We couldn&apos;t scan that page</p>
            <p className="max-w-md text-fg-soft">
              {page?.error ?? "The page didn't load in time."} Double-check the URL is public and
              try again.
            </p>
            <Button href="/" variant="blue" size="md">
              Try another URL
            </Button>
          </div>
        ) : (
          <Report pages={pages} counts={counts} />
        )}

        <footer className="mt-12 border-t border-[var(--color-panel-line)] pt-6 text-sm text-fg-soft">
          Generated by{" "}
          <Link href="/" className="font-bold text-link underline underline-offset-2">
            {SITE_NAME}
          </Link>{" "}
          — automated accessibility checks.
        </footer>
      </div>
    </div>
  );
}

/** The finished single-page report. Split out so the type of `pages` narrows past the scanning gate. */
function Report({
  pages,
  counts,
}: {
  pages: Awaited<ReturnType<typeof getSitePages>>["pages"];
  counts: Awaited<ReturnType<typeof getSitePages>>["counts"];
}) {
  const rules = rollupByRule(pages);
  const conformance = summarizeConformance(rules, { evaluated: true });
  return (
    <>
      <UpsellBanner />

      <div className="mt-8 flex flex-wrap items-center gap-6">
        <ScoreBadge counts={counts} pageCount={pages.length} />
      </div>

      <div className="mt-6">
        <SeveritySummary counts={counts} pageCount={pages.length} />
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-3">
        <div className="panel p-5 sm:p-6 lg:col-span-2">
          <h2 className="mb-4 font-display text-sm font-bold uppercase tracking-wide text-fg-soft">
            WCAG 2.1 conformance
          </h2>
          <WcagScorecard report={conformance} />
        </div>
        <EaaReadiness report={conformance} />
      </div>

      <div className="mt-8">
        <SiteReport rules={rules} pages={pages} counts={counts} />
      </div>

      <UpsellBanner />
    </>
  );
}
