import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";

import { SiteReport } from "@/components/dashboard/SiteReport";
import { WcagScorecard, EaaReadiness } from "@/components/dashboard/Compliance";
import { ScoreBadge } from "@/components/dashboard/ScoreBadge";
import { SeveritySummary } from "@/components/dashboard/severity";
import { PrintButton } from "@/components/dashboard/PrintButton";
import { db, schema } from "@/lib/server/db";
import { getSitePages, rollupByRule } from "@/lib/server/report";
import { summarizeConformance } from "@/lib/wcag";
import { SITE_NAME } from "@/lib/site";

export const metadata: Metadata = { title: "Accessibility report", robots: { index: false } };
export const dynamic = "force-dynamic";

export default async function SharedReportPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  if (!token) notFound();

  const rows = await db
    .select()
    .from(schema.sites)
    .where(eq(schema.sites.shareToken, token))
    .limit(1);
  const site = rows[0];
  if (!site) notFound();

  const { pages, counts } = await getSitePages(site.id);
  const rules = rollupByRule(pages);
  const hasPages = pages.length > 0;
  const conformance = summarizeConformance(rules, { evaluated: hasPages });
  const generated = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="min-h-screen bg-bg">
      <div className="mx-auto w-full max-w-[1000px] px-5 py-10 sm:px-8">
        <div className="flex flex-wrap items-start justify-between gap-4 border-b border-[var(--color-panel-line)] pb-6">
          <div className="min-w-0">
            <p className="mb-2 font-display text-xs font-bold uppercase tracking-[0.12em] text-fg-soft">
              Accessibility report
            </p>
            <h1 className="text-3xl text-fg sm:text-4xl break-words">{site.name}</h1>
            <p className="mt-2 text-sm text-fg-soft">
              {site.origin ? site.origin.replace(/^https?:\/\//, "") : null}
              {site.origin ? " · " : ""}Generated {generated}
            </p>
          </div>
          <PrintButton />
        </div>

        {!hasPages ? (
          <p className="mt-8 text-fg-soft">No scans have completed for this site yet.</p>
        ) : (
          <>
            <div className="mt-8 flex flex-wrap items-center gap-6">
              <ScoreBadge counts={counts} pageCount={pages.length} />
            </div>

            <div className="mt-6">
              <SeveritySummary counts={counts} pageCount={pages.length} />
            </div>

            <div className="mt-6 grid gap-4 lg:grid-cols-3">
              <div className="panel p-5 sm:p-6 lg:col-span-2">
                <h2 className="mb-4 font-display text-sm font-bold uppercase tracking-wide text-fg-soft">
                  WCAG 2.1 conformance
                </h2>
                <WcagScorecard report={conformance} />
              </div>
              <EaaReadiness report={conformance} />
            </div>

            <div className="mt-8">
              <SiteReport rules={rules} pages={pages} counts={counts} />
            </div>
          </>
        )}

        <footer className="mt-12 border-t border-[var(--color-panel-line)] pt-6 text-sm text-fg-soft">
          Generated by{" "}
          <Link href="/" className="font-bold text-link underline underline-offset-2">
            {SITE_NAME}
          </Link>{" "}
          — automated accessibility monitoring.
        </footer>
      </div>
    </div>
  );
}
