import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { PrintButton } from "@/components/dashboard/PrintButton";
import { getPublishedStatement } from "@/lib/server/statement";
import { StatementBody } from "@/components/dashboard/StatementBody";
import { SITE_NAME } from "@/lib/site";

export const metadata: Metadata = {
  title: "Accessibility statement",
  // Hosted on our domain; the owner publishes the canonical copy on their own site (export route),
  // so we keep the hosted version out of search results.
  robots: { index: false },
};
export const dynamic = "force-dynamic";

export default async function PublicStatementPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  if (!token) notFound();

  const loaded = await getPublishedStatement(token);
  if (!loaded) notFound();
  const { model } = loaded;

  return (
    <div className="min-h-screen bg-bg">
      <div className="mx-auto w-full max-w-[760px] px-5 py-10 sm:px-8">
        <div className="flex flex-wrap items-start justify-between gap-4 border-b border-[var(--color-panel-line)] pb-6">
          <p className="font-display text-xs font-bold uppercase tracking-[0.12em] text-fg-soft">
            Accessibility statement
          </p>
          <PrintButton />
        </div>

        <article className="mt-8">
          <StatementBody model={model} />
        </article>

        <footer className="mt-12 border-t border-[var(--color-panel-line)] pt-6 text-sm text-fg-soft">
          Generated by{" "}
          <Link href="/" className="font-bold text-link underline underline-offset-2">
            {SITE_NAME}
          </Link>{" "}
          — automated accessibility monitoring. Updates automatically as the site is re-scanned.
        </footer>
      </div>
    </div>
  );
}
